version: '3'
services:
  app:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolar
      MYSQL_PASSWORD: 'root'
    ports:
      - '3306:3306'